//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HistoryPayWallet
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> MainOrderID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string HContent { get; set; }
        public Nullable<double> MoneyLeft { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> TradeType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<int> TransportationOrderID { get; set; }
    }
}
