//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Complain
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Amount { get; set; }
        public string IMG { get; set; }
        public string ComplainText { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string OrderCode { get; set; }
        public string OrderShopCode { get; set; }
    }
}
