//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OutStockSessionPackage
    {
        public int ID { get; set; }
        public Nullable<int> OutStockSessionID { get; set; }
        public Nullable<int> SmallPackageID { get; set; }
        public string OrderTransactionCode { get; set; }
        public Nullable<int> MainOrderID { get; set; }
        public Nullable<int> TransportationID { get; set; }
        public Nullable<System.DateTime> DateOutStock { get; set; }
        public Nullable<double> DayInWarehouse { get; set; }
        public Nullable<double> FeeWarehouse { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
