//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppPushNoti
    {
        public int ID { get; set; }
        public string AppNotiTitle { get; set; }
        public string AppNotiMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsPush { get; set; }
        public string Username { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
