//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransportaionOrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> TransportationOrderID { get; set; }
        public string TransportationOrderCode { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ProductType { get; set; }
        public Nullable<bool> IsCheckProduct { get; set; }
        public Nullable<bool> IsPackaged { get; set; }
        public Nullable<bool> IsInsurrance { get; set; }
        public string CODTQCYN { get; set; }
        public string CODTQVND { get; set; }
        public string UserNote { get; set; }
        public string StaffNoteCheck { get; set; }
        public string ProductQuantity { get; set; }
    }
}
