//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public string MenuClass { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> Target { get; set; }
    }
}
