//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Step
    {
        public int ID { get; set; }
        public string StepName { get; set; }
        public string StepIMG { get; set; }
        public Nullable<int> StepIndex { get; set; }
        public string StepLink { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string StepContent { get; set; }
        public string ClassIcon { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    }
}
