//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PayhelpDetail
    {
        public int ID { get; set; }
        public Nullable<int> PayhelpID { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string OrderID { get; set; }
        public string Customer { get; set; }
        public string FriendsAccount { get; set; }
    }
}
