//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderList
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string ShopID { get; set; }
        public string ShopName { get; set; }
        public string Site { get; set; }
        public Nullable<bool> IsForward { get; set; }
        public string IsForwardPrice { get; set; }
        public Nullable<bool> IsFastDelivery { get; set; }
        public string IsFastDeliveryPrice { get; set; }
        public Nullable<bool> IsCheckProduct { get; set; }
        public string IsCheckProductPrice { get; set; }
        public Nullable<bool> IsPacked { get; set; }
        public string IsPackedPrice { get; set; }
        public Nullable<bool> IsFast { get; set; }
        public string IsFastPrice { get; set; }
        public string PriceVND { get; set; }
        public string PriceCNY { get; set; }
        public string FeeShipCN { get; set; }
        public string FeeBuyPro { get; set; }
        public string FeeBuyProCK { get; set; }
        public string FeeWeight { get; set; }
        public string FeeWeightCK { get; set; }
        public string Note { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Status { get; set; }
        public string Deposit { get; set; }
        public string CurrentCNYVN { get; set; }
        public string TotalPriceVND { get; set; }
        public Nullable<int> SalerID { get; set; }
        public Nullable<int> DathangID { get; set; }
        public Nullable<int> KhoTQID { get; set; }
        public Nullable<int> KhoVNID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DepostiDate { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public string AmountDeposit { get; set; }
        public string OrderTransactionCode { get; set; }
        public string OrderTransactionCode2 { get; set; }
        public string OrderTransactionCode3 { get; set; }
        public string OrderTransactionCode4 { get; set; }
        public string OrderTransactionCode5 { get; set; }
        public string FeeShipCNToVN { get; set; }
        public string OrderWeight { get; set; }
        public string OrderTransactionCodeWeight { get; set; }
        public string OrderTransactionCodeWeight2 { get; set; }
        public string OrderTransactionCodeWeight3 { get; set; }
        public string OrderTransactionCodeWeight4 { get; set; }
        public string OrderTransactionCodeWeight5 { get; set; }
        public string ReceivePlace { get; set; }
        public string TQVNWeight { get; set; }
        public string Uname { get; set; }
        public string saler { get; set; }
        public string dathang { get; set; }
        public string khotq { get; set; }
        public string khoVN { get; set; }
    }
}
