//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserList
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public Nullable<double> Wallet { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobilePhonePrefix { get; set; }
        public string MobilePhone { get; set; }
        public string saler { get; set; }
        public string dathang { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> DathangID { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<double> WalletCYN { get; set; }
    }
}
